34,35c34
< vgabios.bin              : VGAFLAGS :=
< #-DVBE -DPCIBIOS
---
> vgabios.bin              : VGAFLAGS := -DVBE -DPCIBIOS
47,48c46
< vgabios.bin              : $(VGA_FILES) biossums
< #$(VGA_FILES) $(VBE_FILES) biossums
---
> vgabios.bin              : $(VGA_FILES) $(VBE_FILES) biossums
